### ISSUE TITLE
Boolean in additionalProperties results in a stacktrace

### ISSUE THREAD

**Issue by AnderssonPer** [asyncee/swagger_codegen#16]
When trying to generate a client for a json file containing `"additionalProperties": false` the generation will fail with the below stacktrace. If replacing all occurances of `"additionalProperties": false` with `"additionalProperties": {}` it works. According to https://swagger.io/docs/specification/data-models/keywords/ it's valid to use booleans.

```
$ swagger_codegen generate swagger.json someproject
Generating from swagger.json to . (someproject)
Loaded schema OpenApi30 for External Job API (v1) with 3 endpoint(s)
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\swagger_codegen.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\typer\main.py", line 211, in __call__
    return get_command(self)()
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\typer\main.py", line 494, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\python39\lib\site-packages\swagger_codegen\cli\main.py", line 45, in generate
    renderer.render(list(endpoints))
  File "c:\python39\lib\site-packages\swagger_codegen\render\renderers\package.py", line 66, in render
    self._render_api(api)
  File "c:\python39\lib\site-packages\swagger_codegen\render\renderers\package.py", line 120, in _render_api
    self._render_endpoint(api_dir, endpoint)
  File "c:\python39\lib\site-packages\swagger_codegen\render\renderers\package.py", line 130, in _render_endpoint
    if endpoint.body_request:
  File "c:\python39\lib\site-packages\swagger_codegen\parsing\endpoint.py", line 45, in body_request
    data_type=make_data_type(self.endpoint.body),
  File "c:\python39\lib\site-packages\swagger_codegen\parsing\data_type_parser.py", line 75, in make_data_type
    inner_type = make_data_type(
  File "c:\python39\lib\site-packages\swagger_codegen\parsing\data_type_parser.py", line 22, in make_data_type
    if field in schema:
TypeError: argument of type 'bool' is not iterable
```

**Comment by asyncee** [comment]
Fixed in 0.1.26, thanks.
