### ISSUE TITLE
Not found http://petstore.swagger.io:8080/api/v3/openapi.json

### ISSUE THREAD

**Issue by jianziqin** [asyncee/swagger_codegen#9]
Hi swagger api team,

READ ME tells to run "swagger_codegen generate http://petstore.swagger.io:8080/api/v3/openapi.json petstore", but this openapi.json file is not existed. 

When I change to use "swagger_codegen generate https://petstore.swagger.io/v2/swagger.json petstore" to start a stub server,  exception is as below:

Generating from swagger.json to . (petstore)
Traceback (most recent call last):
  File "/home/emc/vivian/swagger_codegen-master/env/bin/swagger_codegen", line 8, in <module>
    sys.exit(app())
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/typer/main.py", line 211, in __call__
    return get_command(self)()
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/typer/main.py", line 494, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/swagger_codegen/cli/main.py", line 37, in generate
    base_schema = load_base_schema(uri)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/swagger_codegen/parsing/loaders.py", line 43, in load_base_schema
    add_x_names(schema)
  File "/home/emc/vivian/swagger_codegen-master/env/lib/python3.8/site-packages/swagger_codegen/parsing/loaders.py", line 48, in add_x_names
    for name, schema in schema["components"]["schemas"].items():
KeyError: 'components'

**Comment by asyncee** [comment]
Hello, thanks for pointing out, i have updated readme and example configuration. Swagger.io team have moved to new url: https://petstore3.swagger.io/api/v3/openapi.json, so the correct command is:

`swagger_codegen generate https://petstore3.swagger.io/api/v3/openapi.json petstore`
